import messages from "./hangman.messages";

// This file contains the data and configuration for the Hangman game, including words to guess, categories, difficulty levels, and keyboard layout.

const plantsEN = [
  "Rose",
  "Tulip",
  "Daisy",
  "Sunflower",
  "Lily",
  "Orchid",
  "Daffodil",
  "Marigold",
  "Carnation",
  "Chrysanthemum",
  "Iris",
  "Peony",
  "Hydrangea",
  "Lavender",
  "Pansy",
  "Violet",
  "Begonia",
  "Petunia",
  "Sakura",
  "Camelia",
];
const plantsES = [
  "Rosa",
  "Tulipan",
  "Margarita",
  "Girasol",
  "Lirio",
  "Orquidea",
  "Narciso",
  "Calendula",
  "Clavel",
  "Crisantemo",
  "Iris",
  "Peonia",
  "Hortensia",
  "Lavanda",
  "Pensamiento",
  "Violeta",
  "Begonia",
  "Petunia",
  "Sakura",
  "Camelia",
];

const animalsEN = [
  "Tiger",
  "Elephant",
  "Giraffe",
  "Kangaroo",
  "Dolphin",
  "Cheetah",
  "Hedgehog",
  "Lion",
  "Panda",
  "Koala",
  "Flamingo",
  "Zebra",
  "Sloth",
  "Octopus",
  "Chameleon",
  "Armadillo",
  "Narwhal",
  "Otter",
  "Tortoise",
  "Porcupine",
];
const animalsES = [
  "Tigre",
  "Elefante",
  "Jirafa",
  "Canguro",
  "Delfin",
  "Guepardo",
  "Erizo",
  "Leon",
  "Panda",
  "Koala",
  "Flamenco",
  "Cebra",
  "Perezoso",
  "Pulpo",
  "Camaleon",
  "Armadillo",
  "Narval",
  "Nutria",
  "Tortuga",
  "Puercoespin",
];

const countriesEN = [
  "Argentina",
  "Belgium",
  "Korea",
  "China",
  "Australia",
  "Brazil",
  "Canada",
  "Denmark",
  "Egypt",
  "Finland",
  "Germany",
  "Hungary",
  "Iceland",
  "Japan",
  "Kenya",
  "Mexico",
  "Norway",
  "Portugal",
  "Qatar",
  "Russia",
];
const countriesES = [
  "Argentina",
  "Belgica",
  "Corea",
  "China",
  "Australia",
  "Brasil",
  "Canada",
  "Dinamarca",
  "Egipto",
  "Finalndia",
  "Alemania",
  "Hungria",
  "Islandia",
  "Japon",
  "Kenia",
  "Mexico",
  "Noruega",
  "Portugal",
  "Qatar",
  "Rusia",
];

const fruitsEN = [
  "Apple",
  "Banana",
  "Cherry",
  "Blueberry",
  "Watermelon",
  "Strawberry",
  "Pear",
  "Date",
  "Peach",
  "Fig",
  "Grape",
  "Honeydew",
  "Kiwi",
  "Lemon",
  "Mango",
  "Apricot",
  "Orange",
  "Papaya",
  "Quince",
  "Raspberry",
];
const fruitsES = [
  "Manzana",
  "Platano",
  "Cereza",
  "Arandano",
  "Sandia",
  "Fresa",
  "Pera",
  "Datil",
  "Durazno",
  "Higo",
  "Uva",
  "Melon",
  "Kiwi",
  "Limon",
  "Mango",
  "Albaricoque",
  "Naranja",
  "Papaya",
  "Membrillo",
  "Frambuesa",
];

const colorsEN = [
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Purple",
  "Orange",
  "Pink",
  "Brown",
  "Black",
  "White",
  "Gray",
  "Cyan",
  "Magenta",
  "Turquoise",
  "Crimson",
  "Lavender",
  "Silver",
  "Lilac",
  "Teal",
  "Maroon",
];
const colorsES = [
  "Rojo",
  "Azul",
  "Verde",
  "Amarillo",
  "Morado",
  "Naranja",
  "Rosa",
  "Marron",
  "Negro",
  "Blanco",
  "Gris",
  "Cian",
  "Magenta",
  "Turquesa",
  "Carmesi",
  "Lavanda",
  "Plata",
  "Lila",
  "Bronce",
  "Salmon",
];

// Arrays containing words to guess in English and Spanish for each category.
export const wordsToGuessEN = [
  plantsEN,
  animalsEN,
  countriesEN,
  fruitsEN,
  colorsEN,
];
export const wordsToGuessES = [
  plantsES,
  animalsES,
  countriesES,
  fruitsES,
  colorsES,
];

export const categories = [
  {
    id: 1,
    name: messages.data.categories.plants,
    value: "plants",
  },
  {
    id: 2,
    name: messages.data.categories.animals,
    value: "animals",
  },
  {
    id: 3,
    name: messages.data.categories.countries,
    value: "countries",
  },
  {
    id: 4,
    name: messages.data.categories.fruits,
    value: "fruits",
  },
  {
    id: 5,
    name: messages.data.categories.colors,
    value: "colors",
  },
];

// This array contains the difficulty levels for the game, including the number of guesses allowed for each level.
export const difficultyLevels = [
  {
    id: 1,
    level: messages.data.difficultyLevels.easy,
    numberOfGuesses: 10,
  },
  {
    id: 2,
    level: messages.data.difficultyLevels.medium,
    numberOfGuesses: 7,
  },
  {
    id: 3,
    level: messages.data.difficultyLevels.hard,
    numberOfGuesses: 4,
  },
];

export const keyboardKeysTablet = [
  {
    id: 1,
    row: [
      { id: 1, letter: "Q" },
      { id: 2, letter: "W" },
      { id: 3, letter: "E" },
      { id: 4, letter: "R" },
      { id: 5, letter: "T" },
      { id: 6, letter: "Y" },
      { id: 7, letter: "U" },
      { id: 8, letter: "I" },
      { id: 9, letter: "O" },
      { id: 10, letter: "P" },
    ],
  },
  {
    id: 2,
    row: [
      { id: 11, letter: "A" },
      { id: 12, letter: "S" },
      { id: 13, letter: "D" },
      { id: 14, letter: "F" },
      { id: 15, letter: "G" },
      { id: 16, letter: "H" },
      { id: 17, letter: "J" },
      { id: 18, letter: "K" },
      { id: 19, letter: "L" },
    ],
  },
  {
    id: 3,
    row: [
      { id: 20, letter: "Z" },
      { id: 21, letter: "X" },
      { id: 22, letter: "C" },
      { id: 23, letter: "V" },
      { id: 24, letter: "B" },
      { id: 25, letter: "N" },
      { id: 26, letter: "M" },
    ],
  },
];

export const keyboardKeysPhone = [
  {
    id: 1,
    row: [
      { id: 1, letter: "A" },
      { id: 2, letter: "B" },
      { id: 3, letter: "C" },
      { id: 4, letter: "D" },
      { id: 5, letter: "E" },
      { id: 6, letter: "F" },
      { id: 7, letter: "G" },
      { id: 8, letter: "H" },
      { id: 9, letter: "I" },
      { id: 10, letter: "J" },
      { id: 11, letter: "K" },
      { id: 12, letter: "L" },
      { id: 13, letter: "M" },
      { id: 14, letter: "N" },
      { id: 15, letter: "O" },
      { id: 16, letter: "P" },
      { id: 17, letter: "Q" },
      { id: 18, letter: "R" },
      { id: 19, letter: "S" },
      { id: 20, letter: "T" },
      { id: 21, letter: "U" },
      { id: 22, letter: "V" },
      { id: 23, letter: "W" },
      { id: 24, letter: "X" },
      { id: 25, letter: "Y" },
      { id: 26, letter: "Z" },
    ],
  },
];
